---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - yarn install
      - yarn build
      - yarn test:cov
      - yarn test:e2e
---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo hello world
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: build
    commands:
      - yarn
      - yarn build
      - cp -r * /home/w3itch/nest-drone-demo
      - cd /home/w3itch/nest-drone-demo
      - rm -rf ./thirdparty/games
      - ln -s /var/easyrpg/games ./thirdparty/games
      - rm -rf ./thirdparty/gencache
      - ln -s /var/easyrpg/gencache ./thirdparty/gencache
      - rm -rf ./thirdparty/downloads
      - ln -s /var/easyrpg/downloads ./thirdparty/downloads
      - rm -rf ./thirdparty/rtp
      - cp -R /var/easyrpg/rtp ./thirdparty/rtp
      - pm2 status
trigger:
  branch:
    - main
  event:
    # When a pull request is merged GitHub sends a push hook to drone
    - push

---
kind: signature
hmac: 772bf5ad11a3d9c485195d685884b6774f84baf137326dc8830ac0e37e523b6b

...
