---
kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache-nest-drone-demo
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules

  - name: build
    image: node
    commands:
      - yarn
      - yarn build
      - yarn test:cov

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache-nest-drone-demo
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules

volumes:
  - name: cache-nest-drone-demo
    host:
      path: /tmp/cache-nest-drone-demo

---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo hello world
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: build
    commands:
      - yarn
      - yarn build
      - export PM2_HOME=/home/w3itch/.pm2
      - pm2 status

trigger:
  branch:
    - main
  event:
    # When a pull request is merged GitHub sends a push hook to drone
    - push
---
kind: signature
hmac: c8892c231be9bf0ca6a8c2ef3f3efa16cf0923e54b232d09428a6205631c1373

...
