---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - yarn install
      - yarn build
      - yarn test:cov
      - yarn test:e2e

---
kind: signature
hmac: 289650518f59aa451f2b8c6d42c1d116c181263970aca638b6adf592c789c34a

...
