kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - yarn install
      - yarn build
      - yarn test:cov
      - yarn test:e2e
---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo hello world
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: copy
    commands:
      - cp -r * /home/w3itch/nest-drone-demo
trigger:
  branch:
    - main
