kind: pipeline
type: docker
name: build

steps:
  - name: greeting
    image: alpine
    commands:
      - echo hello
      - echo world
  - name: backend
    image: node
    commands:
      - yarn install
      - yarn build
      - yarn test:cov
