---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node
    commands:
      - yarn install
      - yarn build
      - yarn test:cov
      - yarn test:e2e
---
kind: pipeline
type: ssh
name: ssh-deploy-w3itch-api-prod

server:
  host: api.w3itch.io
  user: w3itch
  ssh_key:
    from_secret: SSH_ID_RSA

steps:
  - name: greeting
    commands:
      - echo hello world
  - name: check-env
    commands:
      - ifconfig
      - pwd
  - name: list-easyrpg-games
    commands:
      - ls /var/easyrpg/games
  - name: build
    commands:
      - yarn
      - ls
      - cd /root
      - ls
      - cd ~/.ssh
      - ls

---
kind: signature
hmac: 289650518f59aa451f2b8c6d42c1d116c181263970aca638b6adf592c789c34a

...
